eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST:http://localhost:8086/eureka/}
  instance:
    instance-id: karen-data-instance
spring:
  application:
    name: karen-data
server:
  port: 8081